### ISSUE TITLE
GUI Manager has failures! 

### ISSUE THREAD

**Issue by eshanized** [Snigdha-OS/snigdhaos-kernel-manager#8]
Following error has been reported - 
```python
┌──[I'm whoami➜ Public IP: 192.168.1.10🔒]
└──╼[SNIGDHA OS]/home/whoami/Desktop/snigdhaos-kernel-switcher
$ Command: sudo python snigdhaos-kernel-switcher.py 

(python:39072): Gtk-WARNING **: 15:51:20.134: Unable to acquire session bus: Error spawning command line “dbus-launch --autolaunch=126cd0d9adfc414ab217c96146532ca2 --binary-syntax --close-stderr”: Child process exited with code 1
MESA-INTEL: warning: ../mesa-24.2.7/src/intel/vulkan/anv_formats.c:763: FINISHME: support YUV colorspace with DRM format modifiers
MESA-INTEL: warning: ../mesa-24.2.7/src/intel/vulkan/anv_formats.c:794: FINISHME: support more multi-planar formats with DRM modifiers
2024-11-26 15:51:23:ERROR > Found error in setup_config() [Errno 2] No such file or directory: '/home/whoami/Desktop/snigdhaos-kernel-switcher/defaults/config.toml'
Traceback (most recent call last):
  File "/home/whoami/Desktop/snigdhaos-kernel-switcher/snigdhaos-kernel-switcher.py", line 27, in do_activate
    win = ManagerGUI(application=self, app_name=app_name, default_context=default_context,app_version=app_version)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/whoami/Desktop/snigdhaos-kernel-switcher/ui/ManagerGUI.py", line 91, in __init__
    if "bootloader" in config_data.keys():
                       ^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'keys'
```

**Comment by iconized** [comment]
@eshanized দাড়া ল্যাওড়া, বেশি চোদায়ো না
